
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE  = 20

WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

MINE_COUNT = 20
MINE_ROW = 1
MINE_COL = 3

BUSH_COUNT = 20
BUSH_ROW = 2
BUSH_COL = 2

FLAG_ROWS = 3
FLAG_COLS = 4


SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part


SOLDIER_NAME = "Soldier"
MINE_NAME = "Mine"
FLAG_NAME = "Flag"
BUSH_NAME = "Bush"