
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE  = 20

WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

MINE_COUNT = 20
MINE_ROW = 1
MINE_COL = 3

BUSH_COUNT = 20
BUSH_ROW = 2
BUSH_COL = 2

FLAG_ROWS = 3
FLAG_COLS = 4


SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part


SOLDIER_NAME = "Soldier"
MINE_NAME = "Mine"
FLAG_NAME = "Flag"
BUSH_NAME = "Bush"

DARK_GREEN = (34, 139, 34)
BLACK = (0, 0, 0)

FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))
